const MIN_HEURISTIC_LINES_WEIGHT = 0;
const MAX_HEURISTIC_LINES_WEIGHT = 1;
const MIN_HEURISTIC_EXCESS_WEIGHT = 0;
const MAX_HEURISTIC_EXCESS_WEIGHT = 1;
export const MIN_MAX_CONFIGS = [[MIN_HEURISTIC_LINES_WEIGHT, MAX_HEURISTIC_LINES_WEIGHT], [MIN_HEURISTIC_EXCESS_WEIGHT, MAX_HEURISTIC_EXCESS_WEIGHT]];

export const DEFAULT_CONFIG = [0.5,0.5];
