const MIN_HEURISTIC_LINES_WEIGHT = 0;
const MAX_HEURISTIC_LINES_WEIGHT = 5;
const MIN_HEURISTIC_EXCESS_WEIGHT = 0;
const MAX_HEURISTIC_EXCESS_WEIGHT = 1;
const MIN_HEURISTIC_BOOST = 0;
const MAX_HEURISTIC_BOOST = 30;
export const MIN_MAX_CONFIGS = [[MIN_HEURISTIC_LINES_WEIGHT, MAX_HEURISTIC_LINES_WEIGHT], [MIN_HEURISTIC_EXCESS_WEIGHT, MAX_HEURISTIC_EXCESS_WEIGHT], [0, 0], [MIN_HEURISTIC_BOOST, MAX_HEURISTIC_BOOST]];

const DEFAULT_HEURISTIC_LINES_WEIGHT = 2;
const DEFAULT_HEURISTIC_EXCESS_WEIGHT = 0.1;
const DEFAULT_HEURISTIC_BOOST = 10;
export const DEFAULT_CONFIG = [DEFAULT_HEURISTIC_LINES_WEIGHT, DEFAULT_HEURISTIC_EXCESS_WEIGHT, 0, DEFAULT_HEURISTIC_BOOST];
